// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using recall_ai.api.Data;

#nullable disable

namespace recall_ai.api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.33");

            modelBuilder.Entity("recall_ai.api.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "john.doe@example.com",
                            FirstName = "John",
                            LastName = "Doe"
                        },
                        new
                        {
                            UserId = 2,
                            Email = "jane.smith@example.com",
                            FirstName = "Jane",
                            LastName = "Smith"
                        },
                        new
                        {
                            UserId = 3,
                            Email = "bob.johnson@example.com",
                            FirstName = "Bob",
                            LastName = "Johnson"
                        },
                        new
                        {
                            UserId = 4,
                            Email = "alice.brown@example.com",
                            FirstName = "Alice",
                            LastName = "Brown"
                        },
                        new
                        {
                            UserId = 5,
                            Email = "charlie.davis@example.com",
                            FirstName = "Charlie",
                            LastName = "Davis"
                        },
                        new
                        {
                            UserId = 6,
                            Email = "emily.miller@example.com",
                            FirstName = "Emily",
                            LastName = "Miller"
                        },
                        new
                        {
                            UserId = 7,
                            Email = "frank.wilson@example.com",
                            FirstName = "Frank",
                            LastName = "Wilson"
                        },
                        new
                        {
                            UserId = 8,
                            Email = "grace.moore@example.com",
                            FirstName = "Grace",
                            LastName = "Moore"
                        },
                        new
                        {
                            UserId = 9,
                            Email = "henry.taylor@example.com",
                            FirstName = "Henry",
                            LastName = "Taylor"
                        },
                        new
                        {
                            UserId = 10,
                            Email = "isabella.anderson@example.com",
                            FirstName = "Isabella",
                            LastName = "Anderson"
                        });
                });

            modelBuilder.Entity("recall_ai.api.Models.UserDiary", b =>
                {
                    b.Property<int>("DiaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("InsertedOn")
                        .HasColumnType("TEXT");

                    b.Property<int>("Mood")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NoteDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DiaryId");

                    b.ToTable("UserDiaries");

                    b.HasData(
                        new
                        {
                            DiaryId = 1,
                            InsertedOn = new DateTime(2024, 10, 10, 11, 23, 49, 169, DateTimeKind.Local).AddTicks(5465),
                            Mood = 0,
                            Note = "Feeling great today!",
                            NoteDate = new DateTime(2024, 10, 10, 11, 23, 49, 169, DateTimeKind.Local).AddTicks(5465),
                            UserId = 1
                        },
                        new
                        {
                            DiaryId = 11,
                            InsertedOn = new DateTime(2024, 10, 10, 11, 23, 49, 169, DateTimeKind.Local).AddTicks(5468),
                            Mood = 1,
                            Note = "Feeling great today!",
                            NoteDate = new DateTime(2024, 10, 10, 11, 23, 49, 169, DateTimeKind.Local).AddTicks(5469),
                            UserId = 1
                        },
                        new
                        {
                            DiaryId = 12,
                            InsertedOn = new DateTime(2024, 10, 10, 11, 23, 49, 169, DateTimeKind.Local).AddTicks(5470),
                            Mood = 2,
                            Note = "Feeling great today!",
                            NoteDate = new DateTime(2024, 10, 10, 11, 23, 49, 169, DateTimeKind.Local).AddTicks(5471),
                            UserId = 1
                        },
                        new
                        {
                            DiaryId = 2,
                            InsertedOn = new DateTime(2024, 10, 10, 11, 23, 49, 169, DateTimeKind.Local).AddTicks(5473),
                            Mood = 0,
                            Note = "Had a productive day.",
                            NoteDate = new DateTime(2024, 10, 10, 11, 23, 49, 169, DateTimeKind.Local).AddTicks(5473),
                            UserId = 2
                        },
                        new
                        {
                            DiaryId = 13,
                            InsertedOn = new DateTime(2024, 10, 10, 11, 23, 49, 169, DateTimeKind.Local).AddTicks(5475),
                            Mood = 0,
                            Note = "Had a productive day.",
                            NoteDate = new DateTime(2024, 10, 10, 11, 23, 49, 169, DateTimeKind.Local).AddTicks(5475),
                            UserId = 2
                        },
                        new
                        {
                            DiaryId = 14,
                            InsertedOn = new DateTime(2024, 10, 10, 11, 23, 49, 169, DateTimeKind.Local).AddTicks(5477),
                            Mood = 1,
                            Note = "Had a productive day.",
                            NoteDate = new DateTime(2024, 10, 10, 11, 23, 49, 169, DateTimeKind.Local).AddTicks(5477),
                            UserId = 2
                        },
                        new
                        {
                            DiaryId = 3,
                            InsertedOn = new DateTime(2024, 10, 10, 11, 23, 49, 169, DateTimeKind.Local).AddTicks(5479),
                            Mood = 0,
                            Note = "Feeling a bit tired.",
                            NoteDate = new DateTime(2024, 10, 10, 11, 23, 49, 169, DateTimeKind.Local).AddTicks(5480),
                            UserId = 3
                        },
                        new
                        {
                            DiaryId = 4,
                            InsertedOn = new DateTime(2024, 10, 10, 11, 23, 49, 169, DateTimeKind.Local).AddTicks(5481),
                            Mood = 0,
                            Note = "Excited about the upcoming event!",
                            NoteDate = new DateTime(2024, 10, 10, 11, 23, 49, 169, DateTimeKind.Local).AddTicks(5482),
                            UserId = 4
                        },
                        new
                        {
                            DiaryId = 5,
                            InsertedOn = new DateTime(2024, 10, 10, 11, 23, 49, 169, DateTimeKind.Local).AddTicks(5484),
                            Mood = 2,
                            Note = "Feeling stressed about work.",
                            NoteDate = new DateTime(2024, 10, 10, 11, 23, 49, 169, DateTimeKind.Local).AddTicks(5485),
                            UserId = 5
                        },
                        new
                        {
                            DiaryId = 6,
                            InsertedOn = new DateTime(2024, 10, 10, 11, 23, 49, 169, DateTimeKind.Local).AddTicks(5487),
                            Mood = 0,
                            Note = "Enjoyed a nice walk.",
                            NoteDate = new DateTime(2024, 10, 10, 11, 23, 49, 169, DateTimeKind.Local).AddTicks(5487),
                            UserId = 6
                        },
                        new
                        {
                            DiaryId = 7,
                            InsertedOn = new DateTime(2024, 10, 10, 11, 23, 49, 169, DateTimeKind.Local).AddTicks(5489),
                            Mood = 1,
                            Note = "Feeling anxious.",
                            NoteDate = new DateTime(2024, 10, 10, 11, 23, 49, 169, DateTimeKind.Local).AddTicks(5490),
                            UserId = 7
                        },
                        new
                        {
                            DiaryId = 8,
                            InsertedOn = new DateTime(2024, 10, 10, 11, 23, 49, 169, DateTimeKind.Local).AddTicks(5492),
                            Mood = 0,
                            Note = "Had a fun day out.",
                            NoteDate = new DateTime(2024, 10, 10, 11, 23, 49, 169, DateTimeKind.Local).AddTicks(5492),
                            UserId = 8
                        },
                        new
                        {
                            DiaryId = 9,
                            InsertedOn = new DateTime(2024, 10, 10, 11, 23, 49, 169, DateTimeKind.Local).AddTicks(5494),
                            Mood = 0,
                            Note = "Feeling motivated to start new projects.",
                            NoteDate = new DateTime(2024, 10, 10, 11, 23, 49, 169, DateTimeKind.Local).AddTicks(5495),
                            UserId = 9
                        },
                        new
                        {
                            DiaryId = 10,
                            InsertedOn = new DateTime(2024, 10, 10, 11, 23, 49, 169, DateTimeKind.Local).AddTicks(5497),
                            Mood = 0,
                            Note = "Enjoying some quiet time.",
                            NoteDate = new DateTime(2024, 10, 10, 11, 23, 49, 169, DateTimeKind.Local).AddTicks(5497),
                            UserId = 10
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
